# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: vlevko <marvin@42.fr>                      +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2017/11/02 16:22:31 by vlevko            #+#    #+#              #
#    Updated: 2017/11/02 16:24:31 by vlevko           ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

SRC = ft_display_file.c

NAME = ft_display_file

ERR = -Wall -Wextra -Werror

all: $(NAME)

$(NAME):
	gcc $(ERR) -o $(NAME) $(SRC)

clean:
	/bin/rm -f *.o

fclean:
	/bin/rm -f $(NAME)
